nodes:
  orthanc:
    host: "localhost"
    port: 4242
    ae_title: "ORTHANC"
    description: "Default Local Orthanc DICOM server"
  
  clinical:
    host: "pacs.hospital.org"
    port: 11112
    ae_title: "CLIN_PACS"
    description: "Clinical PACS server"
  
  research:
    host: "10.10.10.50"
    port: 11112
    ae_title: "RESEARCH"
    description: "Research PACS server"

# Local calling AE titles
calling_aets:
  default:
    ae_title: "MCPSCU"
    description: "Default calling AE title"
  
  modality:
    ae_title: "MODALITY"
    description: "Simulating a modality"
  
  workstation:
    ae_title: "WORKSTATION"
    description: "Clinical workstation"

# Currently selected node
current_node: "orthanc"

# Currently selected calling AE title
current_calling_aet: "default"