# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

WORKDIR /app

# Copy the necessary files
COPY pyproject.toml configuration.yaml README.md ./
COPY src/ ./src/

# Upgrade pip and install the package
RUN pip install --upgrade pip \
    && pip install .

# Set the entrypoint to launch the MCP server using the provided configuration file
ENTRYPOINT ["dicom-mcp", "configuration.yaml"]
