services:
  orthanc:
    image: orthancteam/orthanc
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
    environment:
      - ORTHANC_NAME=HelloWorld